import './global.css'


export const metadata = {
  title: 'DevAgensy',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      {children}
        <main>
        </main>
        </body>
    </html>
  )
}
